PREFIX owl:     <http://www.w3.org/2002/07/owl#>
PREFIX rdf:     <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs:    <http://www.w3.org/2000/01/rdf-schema#>
PREFIX dc:      <http://purl.org/dc/elements/1.1/>
PREFIX dcterms: <http://purl.org/dc/terms/>
PREFIX schema:  <http://schema.org/>
PREFIX edm:     <http://www.europeana.eu/schemas/edm/>

CONSTRUCT {
    ?uri a edm:ProvidedCHO, edm:aggregatedCHO ;
         edm:type "TEXT" ;
         edm:provider ?provider ;
         edm:country "el" ;
         dc:creator ?author ;
         dc:description ?description ;
         dc:type ?genre ;
         dc:subject ?keywords ;
         dc:rights ?license ;
         dc:title ?name ;
         dc:publisher ?publisher ;
         owl:sameAs ?sameAs ;
         dcterms:spatial ?spatial ;
         dcterms:temporal ?temporal ;
         edm:isShownAt ?url .
}
WHERE {
	?uri a schema:Book .
    OPTIONAL { ?uri schema:creator ?author }
    OPTIONAL { ?uri schema:description ?desc }
    OPTIONAL { ?uri schema:genre ?genre . 
               FILTER (lang( ?genre) = "en")
               BIND(str(?genre) as ?dc_genre)
             }
    OPTIONAL { ?uri schema:image ?image }
    OPTIONAL { ?uri schema:keywords ?keywords }
    OPTIONAL { ?uri schema:license ?license }
    OPTIONAL { ?uri schema:name ?name }
    OPTIONAL { ?uri schema:provider ?provider }
    OPTIONAL { ?uri schema:publisher ?publisher }
    OPTIONAL { ?uri schema:sameAs ?sameAs }
    OPTIONAL { ?uri schema:spatial ?spatial }
    OPTIONAL { ?uri schema:temporal ?temporal }
    OPTIONAL { ?uri schema:url ?url }
}